name: Build
on: 
  push:
  pull_request:
jobs:
  build-tools:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Build tools
        run: cd tools && CGO_ENABLED=0 go build -o . -buildvcs=false ./cmd/...
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            tools/sfwatch
            tools/sfscrape
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Build frontend
        run: cd frontend && npm ci && npm run build
